spring:
  application:
    name: "chapter02"
  profiles:
    active: "development"
service:
  message:
    type: "simple"
    text: "hello"
---
spring:
  config:
    activate:
      on-profile: "development"
service:
  message:
    text: "hi"
---
spring:
  config:
    activate:
      on-profile: "production"
service:
  message:
    type: "advanced"
    text: "welcome"