spring:
    application:
        name: "chapter05"
    data:
        mongodb:
            uri: "mongodb://localhost:27017"
            database: "microservices"
    jackson:
        default-property-inclusion: NON_NULL